spring.application.name=ASM
server.port=8181

# 1. URL kết nối (Nhớ đổi tên Database cho đúng với tên bạn đã tạo)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=J6Assignment;encrypt=true;trustServerCertificate=true

# 2. Tài khoản SQL Server (Mặc định thường là sa)
spring.datasource.username=lyan
spring.datasource.password=123456

# 3. Driver (Bắt buộc cho SQL Server)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Hibernate Dialect (Chỉ rõ cho Hibernate biết đây là SQL Server)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Log SQL ra console để dễ debug
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Cho phép upload ảnh tối đa 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Đăng nhập bằng gg
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8181/login/oauth2/code/google